spring.application.name=uno

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Hibernate
spring.jpa.hibernate.ddl-auto=update


# Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=boeckermachtnurshitundbekommtnixgebacken18032026sonhdingduesel
jwt.expiration=1000000000000000000